CREATE TABLE IF NOT EXISTS user_games(
 id SERIAL PRIMARY KEY,
 user_id INTEGER NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
 game_id INTEGER NOT NULL REFERENCES games(id) ON DELETE CASCADE,
 rank VARCHAR(100),
 is_main BOOLEAN NOT NULL DEFAULT false,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 UNIQUE (user_id, game_id)
)